language: python
env:
  - PYTHON_VERSION=3.7 IPYTHON_KERNEL=python3
before_install:
    - wget -q http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p /home/travis/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes --quiet conda
install:
    - conda create -n testenv --yes pip python=$PYTHON_VERSION
    - source activate testenv
    - python setup.py -q install
    #- pip install -r requirements.txt
script:
    - python unit_test.py
notifications:
  email: false
